"""add attention_needed_deadline to sales

Revision ID: cd1c9060ec8a
Revises: e7b528461f06
Create Date: 2026-03-16 19:59:06.215893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd1c9060ec8a'
down_revision = 'e7b528461f06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attention_needed_deadline', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('attention_needed_deadline')

    # ### end Alembic commands ###
