"""initial schema

Revision ID: e7b528461f06
Revises: 
Create Date: 2026-03-16 19:14:30.391525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7b528461f06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_transfers',
    sa.Column('transfer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amount_php', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=False),
    sa.Column('account_last4', sa.String(length=4), nullable=False),
    sa.Column('transfer_date', sa.DateTime(), nullable=False),
    sa.Column('reconciliation_status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('transfer_id')
    )
    op.create_table('email_processing_log',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gmail_message_id', sa.String(length=255), nullable=False),
    sa.Column('email_type', sa.String(length=30), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.Column('parsed_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('linked_record_type', sa.String(length=100), nullable=True),
    sa.Column('linked_record_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('log_id'),
    sa.UniqueConstraint('gmail_message_id')
    )
    op.create_table('sales',
    sa.Column('sale_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_number', sa.BigInteger(), nullable=False),
    sa.Column('parent_order_number', sa.BigInteger(), nullable=True),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('shoe_name', sa.String(length=500), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=True),
    sa.Column('box_condition', sa.String(length=30), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('amount_made', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sale_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('issue_type', sa.String(length=255), nullable=True),
    sa.Column('discount_offered', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('confirmation_datetime', sa.DateTime(), nullable=True),
    sa.Column('shipment_deadline', sa.DateTime(), nullable=True),
    sa.Column('pickup_address', sa.Text(), nullable=True),
    sa.Column('pickup_window', sa.String(length=255), nullable=True),
    sa.Column('shipment_date', sa.DateTime(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('cancellation_date', sa.Date(), nullable=True),
    sa.Column('cancellation_type', sa.String(length=30), nullable=True),
    sa.Column('cancellation_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tracking_number', sa.String(length=255), nullable=True),
    sa.Column('inventory_match_status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('sale_id')
    )
    op.create_table('subscriptions',
    sa.Column('subscription_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('amount_original', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('original_currency', sa.String(length=3), nullable=False),
    sa.Column('amount_php', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=False),
    sa.Column('next_billing_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_method', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('subscription_id')
    )
    op.create_table('bank_transfer_allocations',
    sa.Column('allocation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.sale_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transfer_id'], ['bank_transfers.transfer_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('allocation_id')
    )
    op.create_table('expenses',
    sa.Column('expense_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount_original', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('original_currency', sa.String(length=3), nullable=False),
    sa.Column('amount_php', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('conversion_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('linked_sale_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['linked_sale_id'], ['sales.sale_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('expense_id')
    )
    op.create_table('inventory',
    sa.Column('inventory_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('shoe_name', sa.String(length=500), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('date_purchased', sa.DateTime(), nullable=False),
    sa.Column('purchase_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('listed_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('linked_sale_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['linked_sale_id'], ['sales.sale_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('inventory_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory')
    op.drop_table('expenses')
    op.drop_table('bank_transfer_allocations')
    op.drop_table('subscriptions')
    op.drop_table('sales')
    op.drop_table('email_processing_log')
    op.drop_table('bank_transfers')
    # ### end Alembic commands ###
